<div class="col-lg-9">
    <h1>Thanks to :</h1>
    <ul class="row  contributor-gallery">
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="https://avatars1.githubusercontent.com/u/10071238?v=3&s=200" />
            <div class="icon-con ">
                <div class="github ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/github.png') ?>" />
                    </a>
                </div>
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="https://avatars1.githubusercontent.com/u/10071238?v=3&s=200" />
            <div class="icon-con ">
                <div class="github ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/github.png') ?>" />
                    </a>
                </div>
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="https://avatars1.githubusercontent.com/u/10071238?v=3&s=200" />
            <div class="icon-con ">
                <div class="github ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/github.png') ?>" />
                    </a>
                </div>
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="https://avatars1.githubusercontent.com/u/10071238?v=3&s=200" />
            <div class="icon-con ">
                <div class="github ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/github.png') ?>" />
                    </a>
                </div>
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="https://avatars1.githubusercontent.com/u/10071238?v=3&s=200" />
            <div class="icon-con ">
                <div class="github ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/github.png') ?>" />
                    </a>
                </div>
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="<?php echo $this->basePath('img/link.png') ?>" />
            <div class="icon-con ">
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="<?php echo $this->basePath('img/github.png') ?>" />
            <div class="icon-con ">
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="<?php echo $this->basePath('img/cup.png') ?>" />
            <div class="icon-con ">
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
        <li class="col-lg-3 col-md-2 col-sm-3 col-xs-4">
            <img class="avatar" src="<?php echo $this->basePath('img/download.png') ?>" />
            <div class="icon-con ">
                <div class="blog ">
                    <a href="">
                        <img src="<?php echo $this->basePath('img/link.png') ?>" />
                    </a>
                </div>
            </div>
        </li>
    </ul>
</div>