<div class="col-lg-9">
    <h1>Pagination example with Zend Framework 2</h1>
    <div class="demo-box">
        <?php
        echo $this->paginationControl(
            $this->paginator,
            'sliding',
            'learn-zf2-pagination/partials/paginator.phtml'
        );
        ?>
        <table class="table">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Category</th>
                    <th class="text-right">Year</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->paginator as $element): ?>
                    <tr>
                        <td><?php echo $element['title'] ?></td>
                        <td><?php echo $element['category'] ?></td>
                        <td class="text-right"><?php echo $element['year'] ?></td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>
