<!--<h1 class="main-title">Ajax module example for Zend framework 2</h1>-->

<div class="col-lg-3 zf2-sidebar">
    <a class="download-button-lg btn btn-success btn-lg">Download</a>
    <br />
    <iframe src="http://ghbtns.com/github-btn.html?user=mdo&repo=github-buttons&type=fork&count=true"
            allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
    <div class="fb-wrap">
        <div class="fb-share-button" data-layout="button_count" data-href="https://developers.facebook.com/docs/plugins/"></div>
    </div>
    <br />
    <br />

    <div class="box-sidebar border-radius">
        <h5 class="title">Other demos</h5>
        <ul>
            <li><a href=""> Learn ajax form </a> </li>
            <li><a href=""> Learn ajax Upload </a> </li>
        </ul>
    </div>


</div>


<div class="col-lg-9">

    <div class="demo-box">
        <div class="col-lg-4">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('learnZF2Ajax', array('action' => 'index')));
            $form->prepare();
            ?>

            <div class="form-group">
                <label><?= $form->get('username')->getLabel(); ?></label>
                <?= $this->formText($form->get('username')) ?>
            </div>
            <div class="form-group">
                <label><?= $form->get('password')->getLabel(); ?></label>
                <?= $this->formText($form->get('password')) ?>
            </div>
            <input type="submit" value="Login" class="btn btn-success btn-lg" />
            <?php
            $this->form()->closeTag();
            ?>
        </div>
    </div>

</div>