<div class="col-lg-9">

    <div class="demo-box">
        <div class="col-lg-4">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('learnZF2Ajax', array('action' => 'index','method' => 'post')));
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

            <div class="form-group">
                <label><?= $form->get('username')->getLabel(); ?></label>
                <?= $this->formText($form->get('username')) ?>
            </div>
            <div class="form-group">
                <label><?= $form->get('password')->getLabel(); ?></label>
                <?= $this->formText($form->get('password')) ?>
            </div>
            <input type="submit" value="Login" class="btn btn-success btn-lg" />
            <?php
            $this->form()->closeTag();
            ?>
        </div>
    </div>

</div>