<div class="col-lg-9">

    <h1>Form with Captcha in ZF2 demo</h1>

    <div class="demo-box">
        <div>
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url(
                'learn-zf2-captcha',
                [
                    'action'     => 'index'
                ]
            ));
            $form->get('captcha_adapter')->setAttributes([
                'onchange' => "$('#captchaForm').submit();",
            ]);

            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

            <div class="form-group">
                <label><?php echo $form->get('captcha_adapter')->getLabel(); ?></label>
                <?php echo $this->formElement($form->get('captcha_adapter'));
                echo $this->formElementErrors($form->get('captcha_adapter')); ?>
            </div>

            <div class="form-group">
                <label><?php echo $form->get('captcha')->getLabel(); ?></label> <br />
                <?php echo $this->formElement($form->get('captcha'));
                echo $this->formElementErrors($form->get('captcha')); ?>
            </div>

            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>

    <p>
        Captcha Image has default location in <code>public/images/captcha</code> that you can set up in <code>imgDir</code> inside options.
    </p>

    <p>
        By the way, you can find <a href="<?php echo $this->url('home') ?>">other examples using Zend Framework 2</a> in our home page :)
    </p>

</div>

<script type="text/javascript">

</script>
