<div class="col-lg-9">

    <h1>Form with Captcha in ZF2 demo</h1>

    <div class="demo-box">
        <div class="col-lg-4">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url(
                'learn-zf2-captcha',
                array(
                    'action'     => 'index'
                )
            ));
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>

            <div class="form-group">
                <label><?php echo $form->get('captcha_adapter')->getLabel(); ?></label>
                <?php echo $this->formElement($form->get('captcha_adapter'));
                echo $this->formElementErrors($form->get('captcha_adapter')); ?>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>

    <p>

    </p>


    <p>
        By the way, you can find <a href="<?php echo $this->url('home') ?>">other examples using Zend Framework 2</a> in our home page :)
    </p>

</div>
