<div class="col-lg-9">
    <h1>Authentication example with Zend Framework 2</h1>
    <div class="demo-box">
        <ul>
            <code>Username:</code> basic
            <br>
            <code>Password:</code> strongpassword
            <br>
            <br>
            <li><a href="learn-zf2-authentication/basic">Basic Authentication</a></li>

            <br>
            <code>Username:</code> basic
            <br>
            <code>Password:</code> strongpassword
            <br>
            <br>
            <li><a href="learn-zf2-authentication/digest">Digest Authentication</a></li>
        </ul>
    </div>

    <p>The <code>Zend\Authentication\Adapter\Http</code> provides an easy way for Apache like authentication in Zend Framework 2 applications.</p>
    <p>It comes with two implementations Basic and Digest HTTP Authentication, which can be combined with two sub components - the class itself or a FileResolver. We are going to use the FileResolver to read the stored credentials and compare them to the submitted values.</p>
    <p>First thing first. There are few important things to know.</p>
    <p>1. We will create a folder with name <b>auth</b> in MODULE_NAME/config/. Inside that folder create two files basic.txt and digest.txt. The file formats are smillar to Apache htpasswd files.
    Basic - &lt;username&gt;:&lt;realm&gt;:&lt;credentials&gt;, here credentials should be written in clear text, e.g.: <b>stanimir:authentication:plaintextpassword</b>.
    Digest - &lt;username&gt;:&lt;realm&gt;:&lt;credentials&gt;, where &lt;credentials&gt; is the md5 hash of all 3 parts, e.g.: <b>stanimir:authentication:dc45122ef294d83e84a8b5a3a6c5356b</b></p>
    <p>2. In the same module where we have just created our auth folder, open module.config.php file and place this code.</p>
    <pre><code class="language-php"><?php echo htmlentities("
    'authentication' => [
        'adapter' => [
            'config' => [
                'accept_schemes' => 'basic digest',
                'realm'          => 'authentication',
                'digest_domains' => '/learn-zf2-authentication',
                'nonce_timeout'  => 3600,
            ],
            'basic' => __DIR__.'/auth/basic.txt',
            'digest' => __DIR__.'/auth/digest.txt',
        ],
    ],")?></code></pre>
    <p>The code tells us which authentication schemes we accept, the realm (must be the same as the realm in the basic/digest.txt files, digest_domains (only when we use digest authentication) is the URL(s) where we want to apply the same valid information, nonce_timeout sets the number of seconds for which the nonce is valid.</p>

    <code>LearnZF2Authentication\Factory</code>
    <pre><code class="language-php"><?php echo htmlentities('
        $config = $serviceLocator->get(\'Config\');
        $authConfig = $config[\'authentication\'][\'adapter\'];
        $authAdapter = new HttpAdapter($authConfig[\'config\']);

        $basic = new FileResolver();
        $digest = new FileResolver();

        $basic->setFile($authConfig[\'basic\']);
        $digest->setFile($authConfig[\'digest\']);

        $authAdapter->setBasicResolver($basic);
        $authAdapter->setDigestResolver($digest);

        return $authAdapter;')?></code></pre>
</div>
