<?php
    /**
     * Holds themes information
     *
     * @var array
     */
    $themes = $this->themes;
?>
<div class="col-lg-9">
    <h1>Themes switcher example with Zend Framework 2</h1>
    <h2>Default theme</h2>

    <div class="demo-box">
        <div class="col-lg-12">
<?php
        foreach ($themes["themes"] as $key => $theme) {
?>
            <ul class="theme">
                <img width="349" height="230" src="/themes/<?=$key."/".$theme["screenshot"]?>">
                <li class="theme-item"><b>Title:</b>&nbsp;<?=$theme["title"]?></li>
                <li class="theme-item"><b>Author:</b>&nbsp;<?=$theme["author"]?></li>
                <li class="theme-item"><b>Description:</b>&nbsp;<?=$theme["description"]?></li>
                <li class="theme-item"><b>Version:</b>&nbsp;<?=$theme["version"]?></li>
                <li class="theme-item"><b>Created on:</b>&nbsp;<?=$theme["date"]?></li>
                <li class="theme-item"><b>Website:</b>&nbsp;<a href="<?=$theme["website"]?>"><?=$theme["website"]?></a></li>

                <form class="form" role="form" method="post" name="<?=$key?>" action="&#x2F;learn-zf2-themes" id="<?=$key?>">
                    <input type="hidden" name="themeName" class="btn blue" value="<?=$key?>">
                    <input type="submit" name="submit" class="btn btn-default" value="Activate">
                </form>
            </ul>
<?php
        }
?>
        </div>
    </div>
    <p>
        By the way, you can find <a href="<?php echo $this->url('home') ?>">other examples using Zend Framework 2</a> in our home page :)
    </p>
</div>

