<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return [
    'modules' => [
        'Application',
        'DoctrineModule',
        'DoctrineORMModule',
        'LearnZF2Ajax',
        'LearnZF2FormUsage',
        'ZendDeveloperTools',
        'ZFTool',
        'LearnZF2Barcode',
        'LearnZF2Pagination',
        'LearnZF2Log',
        'LearnZF2Navigation',
        'LearnZF2Acl',
    ],
    'module_listener_options' => [
        'module_paths' => [
            './module',
            './vendor'
        ],
        'config_glob_paths' => [
            'config/autoload/{,*.}{global,local}.php'
        ],
    ],
];
