<div class="col-lg-9">
    <h1>I18n example with Zend Framework 2</h1>
    <div class="demo-box">
        <fieldset>
            <legend>Sentences in current language</legend>
            <ul>
                <li><?php echo $this->translate('Hello') ?></li>
                <li><?php echo $this->translate('Learn Zend Framework with this tutorials') ?></li>
            </ul>
        </fieldset>

        <fieldset>
            <legend>Sentences always in English</legend>
            <ul>
                <li></li>
            </ul>
        </fieldset>

        <fieldset>
            <legend>Sentences always in Spanish</legend>
            <ul>
                <li></li>
            </ul>
        </fieldset>
    </div>
</div>