<?php echo $this->render('layout/header'); ?>

<div class="container container-main">

    <!-- sidebar -->

    <div class="col-lg-3 zf2-sidebar">

        <div class="donation-box">
            <a href="" class="download-button-lg btn-donate btn btn-info btn-lg">
                <img src="<?php echo $this->basePath('img/cup.png') ?>" alt="donate" style="width: 32px; height: 32px;" />
                Buy us a cup of coffee
            </a>
            <div class="donation-desc">
                Our service is free. But your donation can help us keep running.
                To rent a server and domain, to buy us a cup of coffee, to reduce our activity in paid stuff and make this service better.
                You can send us a donation to BCA Bank, 008 090 8440 in the name of Abdul Malik Ikhsan with Swifcode CENAIDJA. Please confirm to samsonasik@gmail.com after that ;).
            </div>
        </div>
        <a href="<?php echo $this->downloadbuttonlink('zip'); ?>" class="download-button-lg btn btn-success btn-lg">
            <img src="<?php echo $this->basePath('img/download.png') ?>" alt="download" style="width: 32px; height: 32px;" />
            Download module &nbsp; &nbsp; &nbsp;
        </a>
        <br />
        <iframe src="http://ghbtns.com/github-btn.html?user=sitrunlab&repo=LearnZF2&type=fork&count=true"
                allowtransparency="true" frameborder="0" scrolling="0" width="95" height="20"></iframe>
        <div class="fb-wrap">
            <div class="fb-share-button" href="<?php echo $this->serverUrl() . $this->url(); ?>" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>
        </div>
        <br />
        <br />
        <br />


        <div class="box-sidebar border-radius">
            <h5 class="title">Other demos</h5>
            <ul>
                <?php if ($this->layout()->modules_list) { foreach ($this->layout()->modules_list as $list) {
    if ($list->getModuleName() !== $this->layout()->modulenamespace) {
        ?>

                    <li><a href="<?php echo $this->url($list->getModuleRoute());
        ?>"> <?php echo $list->getModuleName();
        ?> </a> </li>

                <?php
        }
    }
}
                ?>
            </ul>
        </div>

    </div>

    <!-- sidebar -->

    <?php echo $this->content; ?>
</div>

<?php echo $this->render('layout/footer'); ?>
