<?php echo $this->render('layout/header'); ?>

        <div class="container-fluid jumbo-home">
            <div class="container">
                <div class="jumbotron">
                    <h2>Welcome to LearnZF2 site</h2>
                    <p>We provide you real live example in using Zend framework 2</p>
                    <p><a class="btn btn-success btn-lg" href="https://github.com/sitrunlab/LearnZF2" target="_blank">Fork us on GitHub &raquo;</a></p>
                </div>
            </div>
        </div>

        <div class="container container-main">
            <?php echo $this->content; ?>
        </div> <!-- /container -->

<?php echo $this->render('layout/footer'); ?>
