<h2>This site contained some grabbed outside resources :</h2>

<ul>
    <li><a href="https://www.iconfinder.com/krasnoyarsk">https://www.iconfinder.com/krasnoyarsk</a></li>
    <li><a href="http://franksouza183.deviantart.com/">http://franksouza183.deviantart.com/</a></li>
    <li><a href="https://www.iconfinder.com/iconsimple">https://www.iconfinder.com/iconsimple</a></li>
    <li><a href="https://www.iconfinder.com/krasnoyarsk">https://www.iconfinder.com/krasnoyarsk</a></li>
</ul>

Any yours that we forgot to add ? submit an <a href="https://github.com/sitrunlab/LearnZF2/issues">issue</a> ;)
