<div class="col-lg-9">
    <h1>Navigation example with Zend Framework 2</h1>
    <div class="demo-box">
        <div class="col-lg-6">
            <fieldset>
                <legend>Default rendering</legend>
                <?php echo $this->navigation('navigation-example')->menu(); ?>
            </fieldset>
        </div>
        <div class="col-lg-6">
            <fieldset>
                <legend>With custom partial</legend>
            </fieldset>
        </div>
    </div>
</div>