<div class="col-lg-9">

    <h1>Ajax Image upload example with Zend Framework 2</h1>

    <div class="demo-box">
        <div class="col-lg-4">
            <button type="button" class="button modal-toggle"><i class="fa fa-upload"></i>Upload images</button>
            <?php
             $this->headScript()->prependFile($this->basePath('/js/ajaxImageUpload.js'));

             /**
              * @var $form AjaxImageUploadForm
              */
            $form = $this->form;
            $form->prepare();
            echo $this->form()->openTag($form);
            echo $this->partial("/imgupload.phtml");
            echo $this->form()->closeTag();
            ?>
        </div>
    </div>

    <p>
        By the way, you can find <a href="<?php echo $this->url('home') ?>">other examples using Zend Framework 2</a> in our home page :)
    </p>
</div>
