<table class="table table-striped">
    <colgroup>
        <col class="col-xs-1">
        <col class="col-xs-7">
    </colgroup>
    <thead>
    <tr>
        <th class="col-lg-3">Modue name</th>
        <th>Description</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>
            Lorem ipsum sadsadasdsa
            <div class="link-module">
                <a href="#" class="glyphicon glyphicon-new-window"></a> &nbsp;
                <a href="#" class="glyphicon glyphicon-cloud-download"></a>
            </div>
        </td>
        <td>Applies the hover color to a particular row or cell</td>
    </tr>
    <tr>
        <td>
            Lorem ipsum sadsadasdsa
            <div class="link-module">
                <a href="#" class="glyphicon glyphicon-new-window"></a> &nbsp;
                <a href="#" class="glyphicon glyphicon-cloud-download"></a>
            </div>
        </td>
        <td>Applies the hover color to a particular row or cell</td>
    </tr>
    <tr>
        <td>
            Lorem ipsum sadsadasdsa
            <div class="link-module">
                <a href="#" class="glyphicon glyphicon-new-window"></a> &nbsp;
                <a href="#" class="glyphicon glyphicon-cloud-download"></a>
            </div>
        </td>
        <td>Applies the hover color to a particular row or cell</td>
    </tr>
    <tr>
        <td>
            Lorem ipsum sadsadasdsa
            <div class="link-module">
                <a href="#" class="glyphicon glyphicon-new-window"></a> &nbsp;
                <a href="#" class="glyphicon glyphicon-cloud-download"></a>
            </div>
        </td>
        <td>Applies the hover color to a particular row or cell</td>
    </tr>
    <tr>
        <td>
            Lorem ipsum sadsadasdsa
            <div class="link-module">
                <a href="#" class="glyphicon glyphicon-new-window"></a> &nbsp;
                <a href="#" class="glyphicon glyphicon-cloud-download"></a>
            </div>
        </td>
        <td>Applies the hover color to a particular row or cell</td>
    </tr>
    </tbody>
</table>

<ul class="pagination">
    <li><a href="#">&laquo;</a></li>
    <li><a href="#">1</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
    <li><a href="#">4</a></li>
    <li><a href="#">5</a></li>
    <li><a href="#">&raquo;</a></li>
</ul>