<div class="jumbotron">
    <h1>Welcome to LearnZF2 site</h1>
    <p>We provide you real Live examples in Using ZF2 </p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/sitrunlab/LearnZF2" target="_blank"><?php echo $this->translate('Fork us on github') ?> &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">List of Examples</h3>
            </div>
            <div class="panel-body">
                <ul>
                    <li><a href="javascript:void(0);">Using Form and Ajax</a></li>
                    <li><a href="javascript:void(0);">Form and the components examples</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
